# Generated by Django 5.0.1 on 2024-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
